api-keys:
    deepseek: ENC[AES256_GCM,data:nYSINRcZVkqV1FEUq1/Vw8az1Nk5HyLnHYFtc8WeDIMhZIU=,iv:Oc4CMmSu5Pvvo0fKPTryH0mUE92Zape4OGB7VaGnm1o=,tag:QQC9/fZL+JANGizvAFYufQ==,type:str]
    tavily: ENC[AES256_GCM,data:Fxt1kzfIVza2HFz2tyzasFCa9h2ffMnu+3MrTgAY7UXeQEnslvWiW8k=,iv:ssY38LMd0uHgDjD1aTlTw6p8ErkRnJ9NP0NqjQT1bOk=,tag:yeoQTLAmWMMhXcXO0hlxeA==,type:str]
sops:
    age:
        - recipient: age1e3z54cy6h8a6daleetpkajzcndst36dlg0jld4x00lcsc9r585dqxk6778
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RFk4L2dvOGFYa09TVTJE
            bVAxYXI1dld1dG9vSTc2d0liNExJY1pjQlRrCjlZVDFYcyt0em5EOWNTYzBrdnpG
            ODZvWWFIdEVtYlpuSHdpYVVFakhEYlkKLS0tIFlRNnlWTHdER3plbnhSc3ZlU0tT
            Tm5FYjhCamVjYzdBZ0NsSlduMnhCeTQKgNJkoQfp18Sii4M+ot5bvvw+Fi+pB87+
            bOKbXvA/eKS4uCHrNZUxmkHrAPZ5SktmLx3qTS7osWwk8ONTnRlGdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:06:30Z"
    mac: ENC[AES256_GCM,data:kysOV6DSrUIWtLyMIHiaoe6XdQJxJZAilInPbOZwO8XB+amK3kRvvJWAjMkrtT5gZ0OnStyhVkVNqVLOSHbgEAufPTUNijk5LfAJ7wPNmwPQ5y65YO9f4UjxzV3K9JAR/7x/LWiL9rb4Pmj7UasbHchwRfGIGBObHUg2LZQYpkc=,iv:GIOKshl1e0Cwj7jr3D2wBVhkhK3O0waFbuf9LKf0rOk=,tag:6yj0uKjPlIAV4D02IQuKag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
