user:
    password: ENC[AES256_GCM,data:4MY49K3t+IRFO1zd6Tt99Yozca8fwvqSddUmeB4BlcFUw9M4jNkOsNZAiw==,iv:SdlrwE7+gRh6rkdBk/p1T4UV6mtj22Gibwt1hYyLkcg=,tag:Ten5IJdKwldYNHo+qvccHg==,type:str]
sops:
    age:
        - recipient: age1e3z54cy6h8a6daleetpkajzcndst36dlg0jld4x00lcsc9r585dqxk6778
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VzF2bUZHejVLcjdXb29q
            SjlacEFZVDR4RGNkTmJZNnVuMGNSSXZPUXlFCjBiU2xvVGRGejdFZDBJdnl3UGEy
            N1ROZE9UTEs4K1ZrQmh5azNXWXdhR2sKLS0tIHRTNGpFbGRObmNIUElwc3VMU250
            OUM0S2h0YXltVjljdVBUdWpsZ3UzdmcKvMitmOBjHEFjuqdQMI13G6DvBHamTYbl
            cl7hCQvCiACu+VmeyORUqGlyepW3BI42nSNqnVr6EzRVb9kSVn+56A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T19:25:08Z"
    mac: ENC[AES256_GCM,data:6SpS86sIItqB2KvQYf5bya7lNa60EKg/NIvLnQAYdtx/OQtXzfh7rS3od0gy7zPgj0YfzntTRMiN8fqZTsN6P+6zpt3OZMl5ckSdWE+S1Z8po6g9BqbpOA2cAL/n9SVtdrXxGdrd6koWccFyaRHJyDYDA4fsNfvo9lwpkwnRKmM=,iv:ajxZdZlTVFTUkhk2o0y19z/a5JMPN3F7B45Z7CTcZVE=,tag:C9rKOJO521J3vqiTHeVSDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
