#ENC[AES256_GCM,data:W2dxsitAXLlj3CYrbcPuXFJYZX/FCsyvZVHwlcqw+O0AF04XohVvyLIPr8bI47xN1sZqzWKekqvB+eB1VXuvH93mVKh0hkhUzfMrmpwc,iv:HLIR+WRoemHx43Vl89ZfAQAcY2qIbKK1anLCSd9J0rY=,tag:D7+Hidy2eiPjFejJh6lWrQ==,type:comment]
#ENC[AES256_GCM,data:7W41li2P8hCLvQpe3SJVJ9SGB3H+qn+6N5mOcQ==,iv:uhsWQCO6gRgVgwu1Zq5T/+36p2991KoGoUwbGKa7+vA=,tag:BY94stLAuItTWdTLn3nlfQ==,type:comment]
user:
    password: ENC[AES256_GCM,data:wdUFLkuJDkCb/yr5faJCwLGv0VIiiRGceSVzUmdl95vrQ7qVKyubfZnjyrcQCdH6UDeSrtGIH3o2ZTu0RxGYHCwHAIb4qdwndQ==,iv:zgoOQxQ5dqvINFv4+SqGtZxYnkIx9wekUwqOe3VBArI=,tag:mtB4mmmCwVmJNKRqY8niew==,type:str]
sops:
    age:
        - recipient: age1e3z54cy6h8a6daleetpkajzcndst36dlg0jld4x00lcsc9r585dqxk6778
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VzF2bUZHejVLcjdXb29q
            SjlacEFZVDR4RGNkTmJZNnVuMGNSSXZPUXlFCjBiU2xvVGRGejdFZDBJdnl3UGEy
            N1ROZE9UTEs4K1ZrQmh5azNXWXdhR2sKLS0tIHRTNGpFbGRObmNIUElwc3VMU250
            OUM0S2h0YXltVjljdVBUdWpsZ3UzdmcKvMitmOBjHEFjuqdQMI13G6DvBHamTYbl
            cl7hCQvCiACu+VmeyORUqGlyepW3BI42nSNqnVr6EzRVb9kSVn+56A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T16:55:26Z"
    mac: ENC[AES256_GCM,data:c3hin7B6RiD+9Lb6JqWsf4j9GXUTc4g3s9x8VLbwCnOZZeBY77MUuM+E31nyKMJf4GKeTCsE7LOSQTXjGZCmUa0xN+qNj/GUwetlWdtnjzm/hL//hNF6Sb6NyK3C4e3kTrBaCzWnpa6oVLeyy0vte5glxXPNe6xo6iJqsGJgkQY=,iv:pJwH8+Hc/6VUFp6KhxZpUudEr2enPL5X4Uj/XbGkbIM=,tag:SwrE0evuIjpX7Si9EtpjUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
